//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsbaBank.Infrastructure.Messaging {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Messaging.IMessageBus")]
    public interface IMessageBus {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageBus/Send", ReplyAction="http://tempuri.org/IMessageBus/SendResponse")]
        void Send(AsbaBank.Core.Messaging.Envelope value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageBus/Send", ReplyAction="http://tempuri.org/IMessageBus/SendResponse")]
        System.Threading.Tasks.Task SendAsync(AsbaBank.Core.Messaging.Envelope value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMessageBusChannel : AsbaBank.Infrastructure.Messaging.IMessageBus, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MessageBusClient : System.ServiceModel.ClientBase<AsbaBank.Infrastructure.Messaging.IMessageBus>, AsbaBank.Infrastructure.Messaging.IMessageBus {
        
        public MessageBusClient() {
        }
        
        public MessageBusClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MessageBusClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessageBusClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessageBusClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Send(AsbaBank.Core.Messaging.Envelope value) {
            base.Channel.Send(value);
        }
        
        public System.Threading.Tasks.Task SendAsync(AsbaBank.Core.Messaging.Envelope value) {
            return base.Channel.SendAsync(value);
        }
    }
}
